### ISSUE TITLE
Sapper issue with initClient

### ISSUE THREAD

**Issue by sriramcms** [dgraph-io/svelte-urql-example#1]
In case of Sapper + Svelte -- since the App.svelte is  generated -  where do i put this.
I tried other places like routes/books.svelte etc but always end up getting "Function called outside component initialization" error

import { initClient } from "@urql/svelte";
  initClient({
    url: "YOUR-SLASH-ENDPOINT"
  });

**Comment by diepoe** [comment]
Did you try to wrap this into an `onMount`?
